[tool.poetry]
name = "pytest-duration"
version = "1.0.0"
description = "Pytest plugin reporting fixtures and test functions execution time."
authors = ["Oleg Blednov <oleg.codev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pytest = ">=4.6"

[tool.poetry.dev-dependencies]
pytest = ">=4.6"
freezegun = "^1.1.0"
pytest-xdist = "^1.34"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
