name: ci

on:
  pull_request:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare for pre-commit run
        run: pip install -r requirements-ci.txt
      - uses: pre-commit/action@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare for tests run
        run: |
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          pytest --showlocals -vv --cov
